#server:
#  port: 8083
#  context-path: /resource
#security:
#  oauth2:
#    client:
#      client-id: client1
#      client-secret: secret1
#    resource:
#      token-info-uri: http://127.0.0.1:8082/auth_server/oauth/check-token
#      jwt:
#        key-uri: http://127.0.0.1:8082/auth_server/oauth/token_key

# 认证服务器地址
auth-server: http://127.0.0.1:10000/auth_server

server:
  port: 8086
security:
  oauth2:
    client:
      client-id: testclient # 授权服务器配置的client id
      client-secret: testclient # 授权服务器配置的client secret
      scope: test
      access-token-uri: ${auth-server}/oauth/token # 获取access token接口
      user-authorization-uri: ${auth-server}/oauth/authorize #  获取Authorization Code接口
    resource:
      token-info-uri: ${auth-server}/oauth/check_token # 验证token的接口
#      user-info-uri: ${auth-server}/user # 一个可以获取认证授权的自定义接口，可以在授权服务器，也可以在其他服务器上
#      prefer-token-info: true # 如果同时配置了token-info-uri 和 user-info-uri，这个现象设置使用哪个取验证授权

